version: 0.2
env:
  variables:
    REPOSITORY_URI: 970853855377.dkr.ecr.ap-southeast-2.amazonaws.com/api-repository
phases:
  pre_build:
    commands:
      - REGISTRY=$(echo $REPOSITORY_URI | cut -d'/' -f1)
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $REGISTRY
  build:
    commands:
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"reservation-api","imageUri":"%s:%s"}]' $REPOSITORY_URI $IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
  discard-paths: yes
