version: 0.2
env:
  variables:
    REPOSITORY_URI: 970853855377.dkr.ecr.ap-southeast-2.amazonaws.com/api-repository # 例: 970853855377.dkr.ecr.ap-southeast-2.amazonaws.com/api-repository
phases:
  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION # commit-ID をタグに
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts: {}
